// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqgTN3DXUXqo_Z18Q0K8yxs_8RYMr5NHU',
    appId: '1:520306408167:web:41abe72e67ca78e266c042',
    messagingSenderId: '520306408167',
    projectId: 'fir-auth-6f295',
    authDomain: 'fir-auth-6f295.firebaseapp.com',
    storageBucket: 'fir-auth-6f295.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXqHmIvoMacSHGh2IhC7Lf7uLpOcXKQDE',
    appId: '1:520306408167:android:f8588ae8d250036c66c042',
    messagingSenderId: '520306408167',
    projectId: 'fir-auth-6f295',
    storageBucket: 'fir-auth-6f295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9TuvpC9tEQX0HH5k3Urid0y6Eg-UAFnI',
    appId: '1:520306408167:ios:bca2fb87080edb1266c042',
    messagingSenderId: '520306408167',
    projectId: 'fir-auth-6f295',
    storageBucket: 'fir-auth-6f295.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9TuvpC9tEQX0HH5k3Urid0y6Eg-UAFnI',
    appId: '1:520306408167:ios:bca2fb87080edb1266c042',
    messagingSenderId: '520306408167',
    projectId: 'fir-auth-6f295',
    storageBucket: 'fir-auth-6f295.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqgTN3DXUXqo_Z18Q0K8yxs_8RYMr5NHU',
    appId: '1:520306408167:web:f52985ff7e58e2fb66c042',
    messagingSenderId: '520306408167',
    projectId: 'fir-auth-6f295',
    authDomain: 'fir-auth-6f295.firebaseapp.com',
    storageBucket: 'fir-auth-6f295.firebasestorage.app',
  );
}
